### PR TITLE
Feature/create sequence like

### PR DESCRIPTION
**Pull request by andrewgiessel**
As discussed in #49.  The naming here is because we inherit from the collections
abstract base class of `Sequence`.  Seqs are coupled to Biopython, Sequences are more generic.

Needs new tests and some documentation, just want to pause here for general feedback and workflow testing.

All current tests pass.

edit for usage:

```python
In [1]: from seqlike.SequenceLike import SequenceLike

In [2]: s = SequenceLike(["abc", "abc", "qwe", "asd"])

In [3]: s
Out[3]: ['abc', 'abc', 'qwe', 'asd']

In [4]: s.to_index()
Out[4]: array([0., 0., 2., 1.])

In [5]: s.to_onehot()
Out[5]: 
array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [6]: s.alphabet
Out[6]: ['abc', 'asd', 'qwe']

In [9]: s2 = SequenceLike([0, 0, 2, 1], alphabet=["abc", "asd", "qwe"], encoding='index')

In [10]: s2
Out[10]: array(['abc', 'abc', 'qwe', 'asd'], dtype=object)

```

### CODE REVIEW

**Comment by andrewgiessel** [comment]
There are some wrinkles around auto-generation of the alphabet.  As it is, there is a `sorted()` (after a set).  I think sorting makes sense, but when I was doing some testing, it switched encodings in ways I didn't expect.  Help there would be good.

**Comment by ericmjl** [comment]
> There are some wrinkles around auto-generation of the alphabet. As it is, there is a sorted() (after a set). I think sorting makes sense, but when I was doing some testing, it switched encodings in ways I didn't expect. Help there would be good.

@andrewgiessel can you describe what the expected behavior and observed behavior were when sorting the alphabet?

**Comment by andrewgiessel** [comment]
> > There are some wrinkles around auto-generation of the alphabet. As it is, there is a sorted() (after a set). I think sorting makes sense, but when I was doing some testing, it switched encodings in ways I didn't expect. Help there would be good.
> 
> @andrewgiessel can you describe what the expected behavior and observed behavior were when sorting the alphabet?

I think I fixed it after that comment. The expected behavior is that an auto generated alphabet is always the same for any valid “word” made of those letters.  An explicitly specified alphabet should override this. In general, alphabet order is important because it determines index/one hot forms.

**Review by ericmjl — CHANGES_REQUESTED** [review]
Confirming here that the code in the PR works on other project code that we've been working on.

Only thing left here is to fix tests, I believe. Then we can merge and cut a release -- I believe 'minor' is the right version bump.

**Pull request merged**
